Repository zeroGone/studylog, pull requests merged in 2021-04, with the labels that each got.

#36 Bug/hedaer view
  web/WEB-INF/views/include/header.jsp
  web/css/reset.css
  web/img/header/notice-active.png
  web/img/header/notice.png
  web/js/header.js
Labels: bug

#38 feat: 블로그 생성 시 멤버들 이메일로 초대 기능
  pom.xml
  src/main/java/io/zerogone/config/WebConfiguration.java
  src/main/java/io/zerogone/controller/BlogMemberAcceptController.java
  src/main/java/io/zerogone/filter/LoginCheckFilter.java
  src/main/java/io/zerogone/model/CurrentUserInfo.java
  src/main/java/io/zerogone/model/UserDto.java
  src/main/java/io/zerogone/model/entity/Blog.java
  src/main/java/io/zerogone/model/entity/BlogMember.java
  src/main/java/io/zerogone/model/entity/BlogMemberInvitationKey.java
  src/main/java/io/zerogone/model/entity/User.java
  src/main/java/io/zerogone/repository/BlogDao.java
  src/main/java/io/zerogone/repository/BlogMemberDao.java
  src/main/java/io/zerogone/repository/BlogMemberInvitationKeyDao.java
  src/main/java/io/zerogone/repository/UserDao.java
  src/main/java/io/zerogone/service/BlogCreateService.java
  src/main/java/io/zerogone/service/BlogMemberAcceptService.java
  src/main/java/io/zerogone/service/BlogMemberCreateService.java
  src/main/java/io/zerogone/service/BlogMemberInviteService.java
  src/main/java/io/zerogone/service/EmailService.java
  src/main/java/io/zerogone/service/InvitationKeyGenerator.java
  src/test/java/io/zerogone/controller/BlogCreateControllerTest.java
  src/test/java/io/zerogone/repository/BlogMemberDaoTest.java
  src/test/java/io/zerogone/repository/BlogMemberInvitationKeyDaoTest.java
  src/test/java/io/zerogone/service/BlogMemberAcceptServiceTest.java
  src/test/java/io/zerogone/service/BlogMemberCreateServiceTest.java
  src/test/java/io/zerogone/service/EmailServiceTest.java
  src/test/java/io/zerogone/service/InvitationKeyGeneratorTest.java
  web/WEB-INF/views/blog_accept.jsp
  web/css/signup.css
  web/img/blog-defualt.png
Labels: dependencies, enhancement

#40 Feat/mypage view
  web/WEB-INF/views/mypage.jsp
  web/css/mypage.css
  web/js/image_upload.js
Labels: enhancement

#41 feat: 유저 프로필 이미지 업데이트 추가
  src/main/java/io/zerogone/config/WebConfiguration.java
  src/main/java/io/zerogone/controller/UserUpdateController.java
  src/main/java/io/zerogone/repository/UserDao.java
  src/main/java/io/zerogone/service/UserUpdateService.java
  src/test/java/io/zerogone/controller/UserUpdateControllerTest.java
  src/test/java/io/zerogone/repository/UserDaoTest.java
  web/WEB-INF/views/mypage.jsp
Labels: enhancement

#42 Feat/update user image
  web/css/reset.css
  web/js/create_blog.js
  web/js/header.js
  web/js/image_upload.js
Labels: enhancement

#43 fix: mypage - .blog 영역
  web/js/mypage.js
Labels: bug, enhancement

#49 Refactor/blog invitation
  db/studylog_ddl.sql
  db/studylog_er_diagram.mwb
  db/studylog_er_diagram.mwb.bak
  src/main/java/io/zerogone/model/entity/BlogInvitationKey.java
  src/main/java/io/zerogone/model/entity/BlogMember.java
  src/main/java/io/zerogone/repository/BlogInvitationKeyDao.java
  src/main/java/io/zerogone/repository/BlogMemberDao.java
  src/main/java/io/zerogone/service/BlogInvitationService.java
  src/main/java/io/zerogone/service/BlogMemberCreateService.java
  src/main/java/io/zerogone/service/InvitationKeyGenerator.java
  src/test/java/io/zerogone/controller/api/BlogCreateControllerTest.java
  src/test/java/io/zerogone/service/BlogInivationAcceptenceServiceTest.java
  src/test/java/io/zerogone/service/EmailServiceTest.java
  src/test/java/io/zerogone/service/InvitationKeyGeneratorTest.java
Labels: enhancement

#54 refactor: 블로그 초대 수락
  src/main/java/io/zerogone/model/entity/BlogMember.java
  src/main/java/io/zerogone/repository/BlogMemberDao.java
  src/main/java/io/zerogone/service/BlogInvitationAcceptenceService.java
Labels: enhancement

#55 Refactor/fetch join
  src/main/java/io/zerogone/model/entity/BlogMember.java
  src/main/java/io/zerogone/repository/BlogMemberDao.java
  src/test/java/io/zerogone/repository/BlogMemberDaoTest.java
Labels: enhancement

#62 feat: 게시글 리스트 페이지 이동 추가
  src/main/java/io/zerogone/controller/PostController.java
  web/WEB-INF/views/include/header.jsp
  web/WEB-INF/views/include/sidebar.jsp
  web/WEB-INF/views/post_list.jsp
  web/css/reset.css
  web/js/sidebar.js
Labels: enhancement
