Repository zeroGone/studylog, pull requests merged in 2021-03, with the labels that each got.

#10 feat/create blog view
  web/WEB-INF/views/mypage.jsp
  web/js/create_blog.js
Labels: enhancement

#14 Feat/mypage blog list
  src/main/java/io/zerogone/blog/model/Blog.java
  src/main/java/io/zerogone/blog/repository/BlogDao.java
  src/main/java/io/zerogone/blog/service/BlogSearchService.java
  src/main/java/io/zerogone/controller/MyPageController.java
  src/main/java/io/zerogone/user/model/User.java
  src/test/java/io/zerogone/controller/MyPageControllerTest.java
  web/WEB-INF/views/mypage.jsp
  web/css/mypage.css
Labels: enhancement

#16 fix/invite blog member
  src/main/java/io/zerogone/user/controller/UserApiController.java
  src/main/java/io/zerogone/user/controller/UserSearchController.java
  src/main/java/io/zerogone/user/model/NoResult.java
  src/test/java/io/zerogone/user/controller/UserApiControllerTest.java
Labels: bug

#17 fix: 멤버초대 본인 입력오류
  web/js/member_invite.js
Labels: bug

#23 Fix/header view
  web/css/reset.css
  web/js/header.js
Labels: bug, invalid

#26 Feat/create blog view
  web/WEB-INF/views/mypage.jsp
  web/js/create_blog.js
  web/js/member_invite.js
Labels: enhancement
